<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please provide the URL to the product_9d1c62</name>
   <tag></tag>
   <elementGuidId>8ece9f1b-bade-4caf-bcc7-6c5cd35d62ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*  Please provide the URL to the product page(s) you are submitting for integration&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2acf5d09-d847-42c8-baa5-91256bae1382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf</value>
      <webElementGuid>1ff93cd1-bcbe-40b6-8cc2-0a9a41c87c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04963d46-e3a2-464a-90f4-9bf8cec945f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf</value>
      <webElementGuid>e64b5184-8962-497a-a299-0eb92c2a4a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a83415e9-79c0-4418-b611-3389e08cdc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf&quot;)</value>
      <webElementGuid>ddef4cd5-cd60-4381-9ac7-d2559ea2218c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf']</value>
      <webElementGuid>d9dbb880-c1a9-49bd-b675-f8aceeaffce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[10]/div/div/input</value>
      <webElementGuid>a95975fd-323f-4049-86f6-0c6315591841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/input</value>
      <webElementGuid>be3a7e26-61d8-4a59-bf00-4b3990278ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf' and @type = 'text' and @id = 'LCP_Please_provide_the_URL_to_the_product_page_s_you_are_submitting_for_integration__cf']</value>
      <webElementGuid>6aaddea6-3dfc-4313-b924-ba6679933274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
