<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Why are you interested in becoming a _babf2a</name>
   <tag></tag>
   <elementGuidId>0586996f-e4c4-468e-9e4a-4e3216a17ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Logitech_Video_Collaboration_Partner__cf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Logitech_Video_Collaboration_Partner__cf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*  Why are you interested in becoming a Logitech Partner?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a57f646-2013-4c5b-a539-ac709a8f3352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Logitech_Video_Collaboration_Partner__cf</value>
      <webElementGuid>0fec66df-d69c-491a-b52d-8f3e5b866fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e96e21a3-18f4-47ac-bb30-073b21bc8b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Logitech_Video_Collaboration_Partner__cf</value>
      <webElementGuid>fc5f5e34-bd19-402e-94c5-a8a83cbeb1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9bf496da-f4bf-4aae-879c-0f4814509856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Logitech_Video_Collaboration_Partner__cf&quot;)</value>
      <webElementGuid>7664735a-41fd-42c8-af22-ff31ace096fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Logitech_Video_Collaboration_Partner__cf']</value>
      <webElementGuid>0a2af1fd-3e4d-49a3-b1cb-e2ce4e1e545c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LogitechVideoCollaborationPartner']/div/div/input</value>
      <webElementGuid>00223e35-30f6-4984-b770-c0a512f0c652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/input</value>
      <webElementGuid>42cff25f-da9d-4e85-818d-c51ea5575bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Logitech_Video_Collaboration_Partner__cf' and @type = 'text' and @id = 'Logitech_Video_Collaboration_Partner__cf']</value>
      <webElementGuid>c335b08f-3471-4b1b-bfb0-44fd9f2fd4c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
