<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Instagram Handle_ctl00ctl00ct_fb243c</name>
   <tag></tag>
   <elementGuidId>ebea1afb-47ca-4af6-b7fd-56c166206b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LCP_Company_Instagram_handle__cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LCP_Company_Instagram_handle__cf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company Instagram Handle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a06a2ff-eeca-4a1c-ac9a-5e544bb73abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_Instagram_handle__cf</value>
      <webElementGuid>ebfdb77a-3cd8-43c1-ad7e-96801f9c93cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6ccf12f-c831-4a0e-8a6e-ffca3626a5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LCP_Company_Instagram_handle__cf</value>
      <webElementGuid>c81dba09-4a5f-4650-8270-a665e68548c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>57f1febb-5efe-423c-921f-23d5786ab63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LCP_Company_Instagram_handle__cf&quot;)</value>
      <webElementGuid>a8269aad-6f0d-473a-b28d-ef32152f6650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LCP_Company_Instagram_handle__cf']</value>
      <webElementGuid>be850bc1-6a91-4052-9f06-fbd8773a0e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[14]/div[2]/div/input</value>
      <webElementGuid>bcd49c05-3d22-4310-9cd3-9e86608f7766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/input</value>
      <webElementGuid>d02e65cb-ef4b-4b5d-97fb-993435f1f671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_Instagram_handle__cf' and @type = 'text' and @id = 'LCP_Company_Instagram_handle__cf']</value>
      <webElementGuid>dac4faa2-2207-458d-a9ab-199c63f9d417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
