<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Legal Company Name (in EnglishLatin a_349961</name>
   <tag></tag>
   <elementGuidId>14575222-2b0d-467a-bdf4-9142fee27eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Legal_Company_Name_in_English__cf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legal_Company_Name_in_English__cf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*  Legal Company Name (in English/Latin alphabet)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6badc095-808a-4e44-b09d-72da14091025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Legal_Company_Name_in_English__cf</value>
      <webElementGuid>f23cbd7c-6be0-4bd8-abe2-a2449611e64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1cc3c9c8-a968-48d2-89bd-6787b2b18117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legal_Company_Name_in_English__cf</value>
      <webElementGuid>2db9f418-dcff-4022-bd60-6ca7a8f4df7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>52ef786b-bcd8-4072-8fd2-4b7ca028df78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legal_Company_Name_in_English__cf&quot;)</value>
      <webElementGuid>c3f6c2db-927e-444d-8803-cef85c578d5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legal_Company_Name_in_English__cf']</value>
      <webElementGuid>8d250215-598a-4883-aa83-962ca5d3b82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_ApplicantForm']/div[4]/div[2]/div/input</value>
      <webElementGuid>fd86dbde-c9aa-4b0a-9d35-7e5ed9c0a1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>01126b94-fb1c-4e6d-ab35-a22464fcd382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Legal_Company_Name_in_English__cf' and @type = 'text' and @id = 'Legal_Company_Name_in_English__cf']</value>
      <webElementGuid>2a64bb5a-aa2c-4d31-b2b5-3f71cc19b8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
