<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Mobile Number_ctl00ctl00ctl00Glo_20e92e</name>
   <tag></tag>
   <elementGuidId>2d68a56d-51ec-4de0-b656-d50ac34b4d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_MemberMobile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_MemberMobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Work Mobile Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21435d1a-d1bd-48e6-a4f1-f22203300eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$MemberMobile</value>
      <webElementGuid>7a150d0e-1146-4024-8e4f-37d317fe3ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4536eb2-0528-4835-bfa7-da2146d09a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_MemberMobile</value>
      <webElementGuid>54b996ee-5761-4128-9a29-91bdd2044ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc918b07-c853-4b71-8177-47818860683e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_MemberMobile&quot;)</value>
      <webElementGuid>3c7762ba-fb11-4daa-81c5-947032f0d996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_MemberMobile']</value>
      <webElementGuid>e20796a7-0973-48d2-a02d-a96c8611bbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[19]/div[2]/div/input</value>
      <webElementGuid>94e96906-6ac2-4d0b-8cf9-3547d8b8ba29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div[2]/div/input</value>
      <webElementGuid>f6558a66-ea57-4254-a5ad-1aca098331a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$MemberMobile' and @type = 'text' and @id = 'GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_MemberMobile']</value>
      <webElementGuid>d91e4071-c99b-434c-b8fd-6b4625fe5d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
