<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Names your Company Does Busines_74ed2b</name>
   <tag></tag>
   <elementGuidId>9b7c3009-17e7-43a2-905e-515a401dd62d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Associated_Doing_Business_As__cf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Associated_Doing_Business_As__cf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Other Names your Company Does Business as&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c2fabbf-2832-433c-92fc-f8262041182e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Associated_Doing_Business_As__cf</value>
      <webElementGuid>1b2517ce-dc50-4814-94b8-b38c9e38aa4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2346c71d-1750-4b08-9a3f-ddd978308b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Associated_Doing_Business_As__cf</value>
      <webElementGuid>09513129-14ce-40a6-a62d-23d58ee311ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f9fdcfc9-accb-4b21-a87e-3178bd0578c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Associated_Doing_Business_As__cf&quot;)</value>
      <webElementGuid>e636244b-219a-4aec-af95-53adb6e3baf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Associated_Doing_Business_As__cf']</value>
      <webElementGuid>bb42de4f-53b8-4c16-9fb7-2db3e9e495da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_ApplicantForm']/div[4]/div[3]/div/input</value>
      <webElementGuid>896b2b0b-4dec-478a-bb4b-52b64892c191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>fe23c106-9d17-4400-bbbf-49939cb22509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Associated_Doing_Business_As__cf' and @type = 'text' and @id = 'Associated_Doing_Business_As__cf']</value>
      <webElementGuid>332e7c39-b6f4-4e57-b4f8-fd61d51cc2e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
