<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Phone Number_ctl00ctl00ctl00Glob_57b009</name>
   <tag></tag>
   <elementGuidId>4455429c-874e-4cfc-892b-8e7d8c4ebbfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_MemberPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_MemberPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*  Work Phone Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbce2873-0482-423f-8947-549d62fc53fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$MemberPhone</value>
      <webElementGuid>a60a79a2-5742-4573-8492-17ccad8ce357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c19d6c4-60a6-44ed-92a9-08d7d1c8e6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_MemberPhone</value>
      <webElementGuid>7db4dc44-3595-4a2d-adb4-cab56ace46da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c4c19648-6e84-4fb5-adb3-c45d0516d90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_MemberPhone&quot;)</value>
      <webElementGuid>a3d803a9-5bed-4042-9b8a-abd1bcf9b8bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_MemberPhone']</value>
      <webElementGuid>15851064-7de0-452d-93a8-f1d9c7d4c0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_ApplicantForm']/div[26]/div/div/input</value>
      <webElementGuid>3ee0a0fb-31b9-4930-ae80-05415501333d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/div/input</value>
      <webElementGuid>e8808c57-6a03-43f6-8933-0702894a715a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$MemberPhone' and @type = 'text' and @id = 'GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistration_MemberPhone']</value>
      <webElementGuid>b1040004-2638-4140-9efb-52952a551436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
