<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Facebook Handle_ctl00ctl00ctl_6bc5da</name>
   <tag></tag>
   <elementGuidId>f80567e8-dd16-4a9c-bbf7-8665bb984154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LCP_Company_Facebook_handle__cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LCP_Company_Facebook_handle__cf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company Facebook Handle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>773f5e33-cc54-4fcc-9ac0-014192a607a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_Facebook_handle__cf</value>
      <webElementGuid>23bcfc06-1d70-492a-8472-beb3d93be4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d624a6a6-1c0d-45c7-930f-f5c3bf50cb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LCP_Company_Facebook_handle__cf</value>
      <webElementGuid>e3d07c98-88c5-4312-8bf6-b584ea96fafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>986150d5-9c7c-4ee9-ba6a-a3e81f358268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LCP_Company_Facebook_handle__cf&quot;)</value>
      <webElementGuid>03ad89e6-1d35-4296-b921-28b7742b805c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LCP_Company_Facebook_handle__cf']</value>
      <webElementGuid>d6452beb-c49b-4ce0-b864-7870bf3d9e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[13]/div[2]/div/input</value>
      <webElementGuid>fd1f6a17-8344-4302-a178-f84be0e8b526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/input</value>
      <webElementGuid>8b7738fe-7473-41d8-be6e-a8bc3479960b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_Facebook_handle__cf' and @type = 'text' and @id = 'LCP_Company_Facebook_handle__cf']</value>
      <webElementGuid>99ed1788-4c39-4ba3-9d08-dfa885300829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
