<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Twitter Handle_ctl00ctl00ctl0_d18c85</name>
   <tag></tag>
   <elementGuidId>3fa5524f-d8e5-4483-be45-6b0af4f9c867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LCP_Company_Twitter_handle__cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LCP_Company_Twitter_handle__cf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company Twitter Handle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>209cd562-40dc-4277-9745-d92ffca2ccfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_Twitter_handle__cf</value>
      <webElementGuid>d842c67b-f338-4126-adea-f3fbefc3191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f5bfbeb-03ef-45b9-8486-bdeb51aad476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LCP_Company_Twitter_handle__cf</value>
      <webElementGuid>e356bb62-5084-471c-9a0a-c98946e2d261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a093bda-c82f-440f-b88d-a54cdf2cd530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LCP_Company_Twitter_handle__cf&quot;)</value>
      <webElementGuid>18172a41-ba81-4acf-b526-dcee94344133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LCP_Company_Twitter_handle__cf']</value>
      <webElementGuid>f7e88644-9ab0-4fa7-812a-1cb60563d6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[13]/div/div/input</value>
      <webElementGuid>d97f0da3-7ab6-49b7-8112-8ebb0e930f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/input</value>
      <webElementGuid>5cf827cf-610d-44e3-ad4c-8cac8322fb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_Twitter_handle__cf' and @type = 'text' and @id = 'LCP_Company_Twitter_handle__cf']</value>
      <webElementGuid>6ed788b1-264f-429b-9b67-33dd59346aed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
