<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company LinkedIn Handle_ctl00ctl00ctl_83666a</name>
   <tag></tag>
   <elementGuidId>8eb7ad41-5ade-4c3f-b643-4f0f0fc0ff8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LCP_Company_LinkedIn_handle__cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LCP_Company_LinkedIn_handle__cf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company LinkedIn Handle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>687fa579-0ed7-467b-b68a-b835dc3813cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_LinkedIn_handle__cf</value>
      <webElementGuid>e1849d56-aeb2-430d-9cbd-c2c2c9ac5dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23051f85-defa-4090-b8d6-32c83143c365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LCP_Company_LinkedIn_handle__cf</value>
      <webElementGuid>fd82771e-4db1-4ad8-b1d6-7ad6b6ebf05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f6ce1ed7-b8d6-4168-b4ae-8bc2afd0497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LCP_Company_LinkedIn_handle__cf&quot;)</value>
      <webElementGuid>68aa258f-2d88-442b-bd80-378f59cb8eea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LCP_Company_LinkedIn_handle__cf']</value>
      <webElementGuid>df571caf-df12-4588-959e-a27b4314820e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[14]/div/div/input</value>
      <webElementGuid>d457cc34-b9f7-4b9b-908d-f2cd4be4e7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/input</value>
      <webElementGuid>3dbe1afa-ad3d-4517-acca-10e725ee7e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_Company_LinkedIn_handle__cf' and @type = 'text' and @id = 'LCP_Company_LinkedIn_handle__cf']</value>
      <webElementGuid>992d3313-5711-4ec2-b4dc-2ec78abe3402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
