<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location of Company Headquarters_ctl0_0913f2</name>
   <tag></tag>
   <elementGuidId>b35cbcc5-8c71-4d5b-9492-80f0e74ff7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Headquarter_Locations__cf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Headquarter_Locations__cf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*  Location of Company Headquarters&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36570e2f-2ff6-48d8-9968-09a9cdeaa00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Headquarter_Locations__cf</value>
      <webElementGuid>a21f605f-8177-499d-a6b5-f87039bf0135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca863fac-720c-47ef-90c6-ce44f5495f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Headquarter_Locations__cf</value>
      <webElementGuid>02284a9d-c0e9-48e9-a0b1-fefc751a432f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4c09c779-1843-4df9-aa0a-df6de3072e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Headquarter_Locations__cf&quot;)</value>
      <webElementGuid>4324128b-1eff-4d85-9035-aa61a5168fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Headquarter_Locations__cf']</value>
      <webElementGuid>b0f05273-4da4-4d67-993d-65634e1cf7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HeadquartersLocations']/div/input</value>
      <webElementGuid>547476d2-89c7-4e2d-a323-ed88b5de929c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>a3111089-9603-4c5a-933c-9fa90f8267ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistration$Headquarter_Locations__cf' and @type = 'text' and @id = 'Headquarter_Locations__cf']</value>
      <webElementGuid>023d7530-2774-4fc1-a821-3648718034a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
