<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Which marketing activities is your or_c3188d</name>
   <tag></tag>
   <elementGuidId>13e386e1-3b75-4ace-8fac-02529577292d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_Which_marketing_activities_is_your_organization_capable_of_independently_supporting_Select_all_t__cf_Prompt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_Which_marketing_activities_is_your_organization_capable_of_independently_supporting_Select_all_t__cf_Prompt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;* Which marketing activities is your organization capable of independently suppo&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e808b3fb-3878-4587-b782-9091680dd461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>LCP_Which_marketing_activities_is_your_organization_capable_of_independently_supporting_Select_all_t__cf</value>
      <webElementGuid>53a7a5e8-097f-4adb-8dca-d38c29db544a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_Which_marketing_activities_is_your_organization_capable_of_independently_supporting_Select_all_t__cf_Prompt</value>
      <webElementGuid>288fc9ac-9702-4db0-a679-86c00be6c6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>75d6903b-b9c8-4a8c-a0ba-9b3802ec9fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*  Which marketing activities is your organization capable of independently supporting? (Select all that apply.)</value>
      <webElementGuid>5371c2a1-dc05-4b47-8791-7d8749bc1a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_Which_marketing_activities_is_your_organization_capable_of_independently_supporting_Select_all_t__cf_Prompt&quot;)</value>
      <webElementGuid>7de2fa35-b776-4eee-bae9-950a696287e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_Which_marketing_activities_is_your_organization_capable_of_independently_supporting_Select_all_t__cf_Prompt']</value>
      <webElementGuid>ac837e29-b7dd-4231-abdc-0c17e243bb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[12]/div/div/label</value>
      <webElementGuid>4781e84f-a9fc-4f90-a375-6a938135df55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::label[3]</value>
      <webElementGuid>2e4220da-e7e7-4ef6-b8e2-555885836dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::label[1]</value>
      <webElementGuid>8eacb9ee-4be2-4e18-905d-768ee5a86901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/label</value>
      <webElementGuid>bff6eb96-fcfe-4004-8224-4b4bb6bdb208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_Which_marketing_activities_is_your_organization_capable_of_independently_supporting_Select_all_t__cf_Prompt' and (text() = '*  Which marketing activities is your organization capable of independently supporting? (Select all that apply.)' or . = '*  Which marketing activities is your organization capable of independently supporting? (Select all that apply.)')]</value>
      <webElementGuid>8a55eec5-ab2a-4f31-8e84-461ba6070ed5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
