<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_What business issue does our joint so_a0cf81</name>
   <tag></tag>
   <elementGuidId>3fcbd451-22c1-4437-970d-84dd42826871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_What_business_issue_does_our_joint_solution_solve__cf_Prompt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_What_business_issue_does_our_joint_solution_solve__cf_Prompt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;* What business issue does our joint solution solve?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>40f91382-4eb4-466a-9242-4628e8b2ef6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>LCP_What_business_issue_does_our_joint_solution_solve__cf</value>
      <webElementGuid>f38c9a36-7f21-42ac-add7-d033a3e6946e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_What_business_issue_does_our_joint_solution_solve__cf_Prompt</value>
      <webElementGuid>beb6a89e-9731-46f3-bfd7-9989b4c1e3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>f766c3d2-baf8-4bc1-b31f-fcaed05c9e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*  What business issue does our joint solution solve?</value>
      <webElementGuid>75ea9f69-5286-4e05-88de-f67ae6be4a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_What_business_issue_does_our_joint_solution_solve__cf_Prompt&quot;)</value>
      <webElementGuid>0eba212d-041f-4a2e-b0c7-1ba1576cea91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_What_business_issue_does_our_joint_solution_solve__cf_Prompt']</value>
      <webElementGuid>dc16904f-a5ed-4d3c-b70a-e253059167b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[8]/div/div/label</value>
      <webElementGuid>4e4eea4b-5798-4430-b92b-c6c7115ff4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::label[1]</value>
      <webElementGuid>278d85f2-4d7e-4fe6-a964-f2e1251494f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/label</value>
      <webElementGuid>c76bba95-78db-45c5-abc8-6184f8dc07b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_LCP_What_business_issue_does_our_joint_solution_solve__cf_Prompt' and (text() = '*  What business issue does our joint solution solve?' or . = '*  What business issue does our joint solution solve?')]</value>
      <webElementGuid>6bbca4d6-e239-4b5a-8d30-1ca461bd63da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
