<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_What additional categorie(s) does you_ba9528</name>
   <tag></tag>
   <elementGuidId>96ad4a1b-cde1-4adf-807e-1bff5280bc03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_Additional_Solution_Categories__cf_Prompt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_Additional_Solution_Categories__cf_Prompt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;* What additional categorie(s) does your solution fall under?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>05e23399-e9f7-4342-919c-bc8563a79bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Additional_Solution_Categories__cf</value>
      <webElementGuid>4361e663-fb9a-4ee4-9641-dc2997e4bd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_Additional_Solution_Categories__cf_Prompt</value>
      <webElementGuid>583a3713-e7ec-41b4-9efe-b280033a0ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>2597b5f7-3dbe-42ed-a340-fe88eebd29e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*  What additional categorie(s) does your solution fall under?</value>
      <webElementGuid>ae92dbb8-3874-4411-bdd1-e16e33756a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_Additional_Solution_Categories__cf_Prompt&quot;)</value>
      <webElementGuid>d2006e3a-6c68-4b65-855e-00ce2897d278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_Additional_Solution_Categories__cf_Prompt']</value>
      <webElementGuid>f600d514-ce26-41cc-a8be-132e61cf59db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[9]/div[2]/div/label</value>
      <webElementGuid>ba5cd23d-d55f-4842-9afe-c41b31f11903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::label[1]</value>
      <webElementGuid>2a196d99-9d80-4179-b310-4f45ee4f76c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/label</value>
      <webElementGuid>fb9cf99a-b3d6-4b5e-a48f-880e9c83c258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_Additional_Solution_Categories__cf_Prompt' and (text() = '*  What additional categorie(s) does your solution fall under?' or . = '*  What additional categorie(s) does your solution fall under?')]</value>
      <webElementGuid>dfab238b-3a6a-487c-afbe-b6dde606304f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
