<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Apple</name>
   <tag></tag>
   <elementGuidId>c8b67d32-934b-4176-a0fb-fa9c188edc05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Other_VC_SW_Licenses_Sold__cf-result-88xu-Apple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-Other_VC_SW_Licenses_Sold__cf-result-88xu-Apple']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Apple&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d890e939-34d5-4047-875c-946f5e3f1479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>54975557-2779-4da2-9d16-6010065063ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Other_VC_SW_Licenses_Sold__cf-result-88xu-Apple</value>
      <webElementGuid>2e4dbab3-112b-41b3-9c2f-5bd32c844cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>124f0c25-90aa-4c41-8e8c-26fc761af0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>744bf256-1280-4cb7-aef3-fd334be682c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apple</value>
      <webElementGuid>bd3a7736-d8f1-44e4-a42c-1ada471c0e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Other_VC_SW_Licenses_Sold__cf-result-88xu-Apple&quot;)</value>
      <webElementGuid>545a02dc-7926-4202-b16e-d7a790224d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Other_VC_SW_Licenses_Sold__cf-result-88xu-Apple']</value>
      <webElementGuid>263052ac-6ba8-47aa-a96a-31559533de23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Other_VC_SW_Licenses_Sold__cf-results']/li</value>
      <webElementGuid>244df9cf-5a77-47af-8e95-f5649dc36b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow All'])[1]/following::li[1]</value>
      <webElementGuid>84e3683e-dbe5-4743-8201-a93e921ccc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject All'])[1]/following::li[1]</value>
      <webElementGuid>c64e7b75-534c-4763-9943-4e6c9d8685e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Jeans'])[2]/preceding::li[1]</value>
      <webElementGuid>11a1a387-24fd-46b7-a58e-610dea926f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cisco WebEx'])[2]/preceding::li[2]</value>
      <webElementGuid>66c8c334-4038-4e2f-a449-75aa0e50b22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>0259cfc6-c9c0-4129-8718-995363c10f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Other_VC_SW_Licenses_Sold__cf-result-88xu-Apple' and (text() = 'Apple' or . = 'Apple')]</value>
      <webElementGuid>c2486d44-ec5e-422e-86e4-0aec31d0f3e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
