<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Automotive</name>
   <tag></tag>
   <elementGuidId>dfac2eed-54c6-4117-a6f6-d13a8ec2bcc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Vertical_Focus__cf-result-23am-Automotive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-Vertical_Focus__cf-result-23am-Automotive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Automotive&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2dc3ea0e-f2d5-47ab-8e6c-451e9537c0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>48371dca-013a-42b2-8546-c859739f7403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Vertical_Focus__cf-result-23am-Automotive</value>
      <webElementGuid>ae826823-7381-4c10-a9dc-55419b027f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>5b34ca93-3018-4cd6-814f-2fd9e31a302f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>daea2642-15f2-44b6-a295-cae66959d066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automotive</value>
      <webElementGuid>8ba3e577-0657-46f7-a10a-faaa48c38ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Vertical_Focus__cf-result-23am-Automotive&quot;)</value>
      <webElementGuid>ab813e94-bdd6-4efe-b324-e74a15f43957</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Vertical_Focus__cf-result-23am-Automotive']</value>
      <webElementGuid>8b83d045-2d93-4502-9606-90d943405e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Vertical_Focus__cf-results']/li</value>
      <webElementGuid>fb688701-dae6-4c7d-978c-3fb9dc19efcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow All'])[1]/following::li[1]</value>
      <webElementGuid>31c8f517-fece-48b1-8e9c-020c81c08c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject All'])[1]/following::li[1]</value>
      <webElementGuid>60a93b70-601f-4540-818b-55d569815d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Construction'])[2]/preceding::li[1]</value>
      <webElementGuid>d27c9415-c4da-414c-954a-66552410ed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consumer'])[2]/preceding::li[2]</value>
      <webElementGuid>b2f1fa7e-6cca-4b0d-8997-3576a66eaa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>0061c48d-9b9c-4354-a009-502e6ba69960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Vertical_Focus__cf-result-23am-Automotive' and (text() = 'Automotive' or . = 'Automotive')]</value>
      <webElementGuid>55c0df6b-05ca-4fd7-af75-2bfd01eab870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
