<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Asia-Pacific</name>
   <tag></tag>
   <elementGuidId>ba8089e1-546b-4434-9f13-90e4b4227702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Which_region_s_are_the_other_offices_in__cf-result-4u85-Asia-Pacific</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-Which_region_s_are_the_other_offices_in__cf-results']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Asia-Pacific&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c3bd20cb-63f1-49dc-a335-89942799d948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>2ea038c2-8685-4502-b4ec-dfb8d2fb3097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Which_region_s_are_the_other_offices_in__cf-result-4u85-Asia-Pacific</value>
      <webElementGuid>f52dffa7-4522-43b2-aaf3-c86bd15e3de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>c4447551-5c63-43a9-8db5-b9de573b95ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>423969fd-b9a9-47c0-84d0-c4d7d31b4559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asia-Pacific</value>
      <webElementGuid>19472720-551b-44a9-a9ff-161685e9674c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Which_region_s_are_the_other_offices_in__cf-result-4u85-Asia-Pacific&quot;)</value>
      <webElementGuid>c6fe2f5b-9b58-42f8-8126-83caa0ff443d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Which_region_s_are_the_other_offices_in__cf-result-4u85-Asia-Pacific']</value>
      <webElementGuid>ae45b537-beed-4f1d-a0ee-9b50c6021097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Which_region_s_are_the_other_offices_in__cf-results']/li</value>
      <webElementGuid>56a4c303-aa4d-466d-ad47-8af5cc36c228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow All'])[1]/following::li[1]</value>
      <webElementGuid>5b14d042-084c-4315-b7e6-10e7318d11f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject All'])[1]/following::li[1]</value>
      <webElementGuid>44f12c68-2ef9-435e-9308-a3071248bd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe, the Middle East and Africa'])[3]/preceding::li[1]</value>
      <webElementGuid>224ea901-27ba-4594-8537-a86c4f3b3209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latin America'])[3]/preceding::li[2]</value>
      <webElementGuid>9508c498-fc0d-4c40-9997-323185684d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>bf532796-73cc-4631-b62d-bb6403085860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Which_region_s_are_the_other_offices_in__cf-result-4u85-Asia-Pacific' and (text() = 'Asia-Pacific' or . = 'Asia-Pacific')]</value>
      <webElementGuid>1bc7cdca-cd20-49ce-aec7-5580274df651</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
