<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Cisco</name>
   <tag></tag>
   <elementGuidId>d5132f36-d3d8-49ff-a7c0-0f4991da0a99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Other_VC_HW_Sold__cf-result-0on3-Cisco</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-Other_VC_HW_Sold__cf-result-0on3-Cisco']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Cisco&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0842b257-c506-4469-b1c1-ad5ce949ea31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>1590b039-f288-41bd-9668-dc78a8864a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Other_VC_HW_Sold__cf-result-0on3-Cisco</value>
      <webElementGuid>afd74135-261b-47b6-8852-c1e2d0916f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>1ab3dbd3-78b1-4334-b515-04f693fbe32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bfea65eb-dbc3-4893-8bb6-a64351161a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cisco</value>
      <webElementGuid>43436d4f-3069-4409-abe6-a14c9d23265d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Other_VC_HW_Sold__cf-result-0on3-Cisco&quot;)</value>
      <webElementGuid>946b0712-ed87-48eb-a9b0-37299aed802a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Other_VC_HW_Sold__cf-result-0on3-Cisco']</value>
      <webElementGuid>9ece9a4b-c0cf-45a1-b774-c1b82659d84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Other_VC_HW_Sold__cf-results']/li</value>
      <webElementGuid>4fb39434-e6ca-49e2-a162-3c8c743e10f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow All'])[1]/following::li[1]</value>
      <webElementGuid>4c9881f2-c007-4285-9832-e1d571d8362c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject All'])[1]/following::li[1]</value>
      <webElementGuid>e62e5181-b23f-4f12-8efa-244dbb8c9cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crestron'])[2]/preceding::li[1]</value>
      <webElementGuid>f480d998-a3e8-446b-a36d-877389776487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[3]/preceding::li[2]</value>
      <webElementGuid>e68b67e9-6885-4a5f-b1c1-bb0e45c926dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>d5a8ffaf-aa9b-4b00-b526-eec34f323845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Other_VC_HW_Sold__cf-result-0on3-Cisco' and (text() = 'Cisco' or . = 'Cisco')]</value>
      <webElementGuid>43545bbe-77be-4c33-a2a8-d9406b7c48b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
