<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Compute</name>
   <tag></tag>
   <elementGuidId>7916d4af-a4e3-4d01-b70a-31caa16a7dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-Additional_Solution_Categories__cf-result-8rin-Compute']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-Additional_Solution_Categories__cf-result-8rin-Compute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Compute&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>748dfdb6-0e7d-4a97-b90b-ad2eb853c347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>8c2119a7-f39e-4825-b899-d6e6ff1c868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Additional_Solution_Categories__cf-result-8rin-Compute</value>
      <webElementGuid>db7ba8b1-d273-4c93-a65c-8b46bf76dc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>fa3a555b-8f28-4f74-8c96-1de14607793a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d56a164e-dcd1-4cf3-8da8-1a1d5fd7b04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compute</value>
      <webElementGuid>485ba07e-def4-4ba5-ad6d-d87a72e082b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Additional_Solution_Categories__cf-result-8rin-Compute&quot;)</value>
      <webElementGuid>59cc544e-4a9c-46f2-bd0a-29b941c2bcf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Additional_Solution_Categories__cf-result-8rin-Compute']</value>
      <webElementGuid>eb06445e-9157-4b21-be71-eee17964d690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Additional_Solution_Categories__cf-results']/li</value>
      <webElementGuid>986dc7bc-ef2c-4251-ad18-7b2e8275593c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow All'])[1]/following::li[1]</value>
      <webElementGuid>70c38714-44d3-4b0d-811e-64fbcbb932cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Signage'])[3]/preceding::li[1]</value>
      <webElementGuid>eeeb3ba4-50da-4a0c-a3bf-c2883f824233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[3]/preceding::li[2]</value>
      <webElementGuid>6dcf643c-e149-48ea-8481-c0b677985a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>1f4c9db6-8ae3-4323-b241-7149017b34d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Additional_Solution_Categories__cf-result-8rin-Compute' and (text() = 'Compute' or . = 'Compute')]</value>
      <webElementGuid>a37ba7df-3825-4bb9-8590-82bfaa883f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
