<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Gaming_1</name>
   <tag></tag>
   <elementGuidId>c37aad6c-a042-4dc2-82a1-38dadc7ff875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Logitech_Products_You_Expect_to_Sell__cf-result-xhqx-Gaming</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-Logitech_Products_You_Expect_to_Sell__cf-result-xhqx-Gaming']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Gaming&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>67f8d2b2-616e-49e7-929a-22459f013947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>335485a3-55bf-4563-bfed-98ddafd26297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Logitech_Products_You_Expect_to_Sell__cf-result-xhqx-Gaming</value>
      <webElementGuid>85fca2a4-0d39-4064-bbdd-e1e8450b338a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>d7336204-aad2-4dd4-a06f-8b8c541d47c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca2c63ab-a04c-4412-ab46-3e1dfa5a0241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gaming</value>
      <webElementGuid>0dabaf88-a2ae-4578-917e-f37bb12dcc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Logitech_Products_You_Expect_to_Sell__cf-result-xhqx-Gaming&quot;)</value>
      <webElementGuid>bf094d92-8c17-466f-a37a-426c49db91c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Logitech_Products_You_Expect_to_Sell__cf-result-xhqx-Gaming']</value>
      <webElementGuid>2aef1370-eecf-4f7f-b4e8-2dd2a3b95059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Logitech_Products_You_Expect_to_Sell__cf-results']/li[2]</value>
      <webElementGuid>2f87129c-0b61-47c1-b39f-85d36d5381bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories &amp; Peripherals'])[3]/following::li[1]</value>
      <webElementGuid>49fe0ea0-ede6-4c38-83f5-43b70dee9913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow All'])[1]/following::li[2]</value>
      <webElementGuid>ce2b0976-fc81-405a-947c-03d90b86828e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Headsets &amp; Speakers'])[3]/preceding::li[1]</value>
      <webElementGuid>ff09006e-9bf6-4fe6-a60a-058e485bec45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mice &amp; Keyboards'])[3]/preceding::li[2]</value>
      <webElementGuid>4af76a8c-e5b5-45d6-a256-ee417843322f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[2]</value>
      <webElementGuid>af9fbefe-d7c4-4579-b24d-417830d32d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Logitech_Products_You_Expect_to_Sell__cf-result-xhqx-Gaming' and (text() = 'Gaming' or . = 'Gaming')]</value>
      <webElementGuid>03d2f65d-7f0a-425b-9ab4-12f2f578584f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
