<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Please provide the URL to the prod_3c7354</name>
   <tag></tag>
   <elementGuidId>4b58f4c8-e600-4b14-ac59-e65187c67fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*  What are the top three goals you would like to accomplish in the first 6 months of our partnership?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>db1cab01-8393-4f8c-ac52-51b8404114e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf</value>
      <webElementGuid>be6d9282-67c0-42e0-b978-01b5a589a447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>55286fcc-0fcb-460d-86a2-89927045a2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8375c921-0510-4a1b-ac30-0bd25990bd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf</value>
      <webElementGuid>268ae88c-19ac-4039-8553-7311589553d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4ec17673-41af-4674-84a0-bed71fb24df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf&quot;)</value>
      <webElementGuid>98994aab-fb80-4493-baeb-29fe1190a7de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf']</value>
      <webElementGuid>858704fb-4f30-471e-88db-0454de99605a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[11]/div/div/textarea</value>
      <webElementGuid>43e6fde8-3417-44e5-adfa-a53ca98cc953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/textarea</value>
      <webElementGuid>8a6f55e6-4baf-47a9-8e73-7e3db04859c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf' and @id = 'LCP_What_are_the_top_three_goals_you_would_like_to_accomplish_in_the_first_6_months_of_our_partnersh__cf']</value>
      <webElementGuid>02b3c5ca-63f9-4a88-9ec9-505239fc05f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
