<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_What business issue does our joint_f20be8</name>
   <tag></tag>
   <elementGuidId>74e1ced9-8682-4a7e-8393-738ad090f681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='LCP_What_business_issue_does_our_joint_solution_solve__cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LCP_What_business_issue_does_our_joint_solution_solve__cf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*  What business issue does our joint solution solve?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c03a4619-bd62-4ed5-989e-137ad92bb113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_What_business_issue_does_our_joint_solution_solve__cf</value>
      <webElementGuid>310df0c1-dff8-41a0-879a-594886451026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a2b76f86-f71a-47c0-b2e9-32bb6fd263e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>54903cdb-d2f6-442e-9639-a6a8ad43f393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LCP_What_business_issue_does_our_joint_solution_solve__cf</value>
      <webElementGuid>4efaaf4d-7dc2-426a-b1c8-17bebc202e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7181992e-a44f-4165-b444-20f2bd78308d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LCP_What_business_issue_does_our_joint_solution_solve__cf&quot;)</value>
      <webElementGuid>8ab240ac-952c-4af3-8dbe-8fb6c64eb7b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='LCP_What_business_issue_does_our_joint_solution_solve__cf']</value>
      <webElementGuid>613b3993-32f8-4f4a-9f0a-bd4911ae3628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_AccountRegistrationAlliance_ApplicantForm']/div[8]/div/div/textarea</value>
      <webElementGuid>813ff084-a03b-464d-895a-b2147e4a0bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3dbb888f-d3f8-4382-9133-567f7f3d39bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$AccountRegistrationAlliance$LCP_What_business_issue_does_our_joint_solution_solve__cf' and @id = 'LCP_What_business_issue_does_our_joint_solution_solve__cf']</value>
      <webElementGuid>2fefea5e-4683-4c2c-a04a-fdb0cd300ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
