<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lead Test Lead was created</name>
   <tag></tag>
   <elementGuidId>cd544394-9abc-4408-a5c8-300481b4f7be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.toastMessage.slds-text-heading--small.forceActionsText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::span[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Lead \&quot;Test Lead\&quot; was created.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f6be13d-b474-4d4f-b96f-2032e5e2ce88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toastMessage slds-text-heading--small forceActionsText</value>
      <webElementGuid>f1109b86-956f-4850-a33f-cfbca0704c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>947:0</value>
      <webElementGuid>cd820ac4-0e02-4098-8205-042e20834fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceActionsText</value>
      <webElementGuid>af687c69-ac55-492e-8569-686e72ca800f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lead &quot;Test Lead&quot; was created.</value>
      <webElementGuid>bfcf44c6-1750-4ce4-b650-f8268face1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastDescription931:0&quot;)/span[@class=&quot;toastMessage slds-text-heading--small forceActionsText&quot;]</value>
      <webElementGuid>cc29077e-2a78-4c7f-9745-fc9f6e2b55f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastDescription931:0']/span</value>
      <webElementGuid>319adab9-c4a3-4ee6-9416-3086180763fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::span[1]</value>
      <webElementGuid>c3487561-69fb-45c8-8438-fcfd32d693bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::span[5]</value>
      <webElementGuid>d7bf599e-89cd-433e-920b-3afcc2ff5549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Control + F6 to navigate to the next toast notification or focusable region.'])[1]/preceding::span[1]</value>
      <webElementGuid>c65bd067-4f06-49df-9e31-989a52396a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/span</value>
      <webElementGuid>cc395029-fcb8-4984-af08-aec1665cfe41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lead &quot;Test Lead&quot; was created.' or . = 'Lead &quot;Test Lead&quot; was created.')]</value>
      <webElementGuid>7cc5e5e9-40ef-4021-b9c5-a3f64fca1c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
