<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage Team Members</name>
   <tag></tag>
   <elementGuidId>5a079017-d0a0-4dc8-a258-6c5d85dc455c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_InternalBodyContent_BodyContent_ManageTeamMembersLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='GlobalBodyContent_InternalBodyContent_BodyContent_ManageTeamMembersLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Manage Team Members&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15eb6a39-5537-47e1-b971-a7fb526c1963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../../Administration/Manage</value>
      <webElementGuid>54fb9c53-a10b-4354-bd7a-05aad26ee78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_InternalBodyContent_BodyContent_ManageTeamMembersLink</value>
      <webElementGuid>c6030833-76dc-4a86-b8ed-5bc9bac92cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>744185ff-fa1c-4f54-a412-650709b6ec62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Manage Team Members</value>
      <webElementGuid>f01a2cc1-d011-4445-bc53-51e9a154e580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_InternalBodyContent_BodyContent_ManageTeamMembersLink&quot;)</value>
      <webElementGuid>7c569ae8-c7fe-446b-b17c-1e9a7fc77fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='GlobalBodyContent_InternalBodyContent_BodyContent_ManageTeamMembersLink']</value>
      <webElementGuid>9b86cc69-9bb7-44b3-989c-e618db56d023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_InternalBodyContent_BodyContent_ManageTeamMembersPanel']/div/p/a</value>
      <webElementGuid>886e3984-0033-4efd-909b-377be798f262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage Team Members')]</value>
      <webElementGuid>e7c65c17-0f22-4e6f-a24d-9e20b982d2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::a[2]</value>
      <webElementGuid>763ad1a8-089a-4f08-a598-5160c0b1dd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Privacy Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>928f7abc-e702-490f-9105-68592b166a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../../../Administration/Manage')]</value>
      <webElementGuid>e6b5251a-2fa3-4d62-8cf7-9e1c6bfa976b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p/a</value>
      <webElementGuid>5992d80d-6cf2-474e-8b2b-c0db46c752cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../../Administration/Manage' and @id = 'GlobalBodyContent_InternalBodyContent_BodyContent_ManageTeamMembersLink' and (text() = ' Manage Team Members' or . = ' Manage Team Members')]</value>
      <webElementGuid>bf5da6e6-102b-40a4-8d35-33212654811d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
