<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Password_ctl00ctl00ctl00GlobalBod_a199ed</name>
   <tag></tag>
   <elementGuidId>0b10f92a-3914-40e1-986a-944334ef0c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_ExternalBodyContent_BodyContent_ChangePasswordControl_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_ChangePasswordControl_Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;New Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d4c9bbe-b151-4e45-a417-d25f2fc28f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$ChangePasswordControl$Password</value>
      <webElementGuid>8767c6c4-8a87-461b-85f8-3ea41cd6a7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8f5e2281-8ce3-4671-9c2c-caaae3e905a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_ExternalBodyContent_BodyContent_ChangePasswordControl_Password</value>
      <webElementGuid>daef2c59-8cc8-42b6-bf45-212fd85ee2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ade12cf0-3650-48ba-8937-9fd4a9569b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>31e1e580-e10c-475d-8ae9-8f3b868e8937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New Password</value>
      <webElementGuid>f3b8f788-0045-494f-99d2-9b5520c0460c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_ExternalBodyContent_BodyContent_ChangePasswordControl_Password&quot;)</value>
      <webElementGuid>08f0426d-5cd1-495a-b3fe-b3d0d8d0e841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_ChangePasswordControl_Password']</value>
      <webElementGuid>892bb447-e1e0-43fd-ba9c-9afa83fd5eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='page-content']/section/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>22897240-3c80-441c-81dd-0105d2e8f295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5f0ed035-3794-4039-bed5-1782b24bcd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$ChangePasswordControl$Password' and @type = 'password' and @id = 'GlobalBodyContent_ExternalBodyContent_BodyContent_ChangePasswordControl_Password' and @placeholder = 'New Password']</value>
      <webElementGuid>b0db0132-27f4-4887-a8ea-ac313943ba1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
