<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit</name>
   <tag></tag>
   <elementGuidId>70d1d158-04d9-457f-aa6f-6ae61d1c25d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_InternalBodyContent_BodyContent_btnSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='GlobalBodyContent_InternalBodyContent_BodyContent_btnSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81588415-b3e5-487a-9cef-65e13decf8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_InternalBodyContent_BodyContent_btnSubmit</value>
      <webElementGuid>5c5a3a9a-3f6a-4250-bcf5-1ab2909b66ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>c6ec6a23-a6c8-4bb7-8ffd-5d43142b5675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$btnSubmit','')</value>
      <webElementGuid>f342dd82-fd80-43c6-a14c-ea98c6ea1c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>4107cdcd-136f-46bb-8cb1-750fe57da1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_InternalBodyContent_BodyContent_btnSubmit&quot;)</value>
      <webElementGuid>6bdb1f8f-6ac2-4d06-bdd8-0ab576de3be7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='GlobalBodyContent_InternalBodyContent_BodyContent_btnSubmit']</value>
      <webElementGuid>18cd8a87-2fe3-4f9e-9a7a-7885ce1a71c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GlobalBodyContent_InternalBodyContent_BodyContent_FormButton']/div/div/p[2]/a</value>
      <webElementGuid>f3ed5f2c-6be4-4557-83ff-0df535d748b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Submit')]</value>
      <webElementGuid>b12536aa-7947-4710-a248-e7873294561e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes, I would like to subscribe to marketing emails and newsletters'])[1]/following::a[1]</value>
      <webElementGuid>d8d48d46-7aa3-4dbb-beaa-918bd2a2c4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[2]</value>
      <webElementGuid>76485eda-24ec-4bdd-87f4-9441ed9699a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[2]/preceding::a[1]</value>
      <webElementGuid>33ba7c70-a63b-48d9-afb1-5c73e641d715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>cd890ebf-f299-41f8-9a28-8a562c10a35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$btnSubmit','')&quot;)]</value>
      <webElementGuid>8e1dead1-c2a8-4302-8446-e47864908922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>a8339869-e33c-492b-9ac5-c8c0d3420f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'GlobalBodyContent_InternalBodyContent_BodyContent_btnSubmit' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$btnSubmit&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>626d3b68-bebc-4a50-9cc8-ad8dd01e0462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
