<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Profile</name>
   <tag></tag>
   <elementGuidId>f25087bd-26e0-45c0-9283-1fa945294c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PageTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PageTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PageTitle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e09ae55-85a3-4420-9cd4-caf7b621352e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PageTitle</value>
      <webElementGuid>fd72ee09-3a24-4e49-94d0-0c57ed270226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	My Profile
</value>
      <webElementGuid>2a79203d-80aa-45f4-b330-062a582ae7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageTitle&quot;)</value>
      <webElementGuid>4c5fea22-1dd5-48ec-8d3a-43a562683160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='PageTitle']</value>
      <webElementGuid>175552d6-92d9-48a8-a7d7-cd003f10671a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='page-content']/div[2]/div/h1/div</value>
      <webElementGuid>862a3331-8738-4cf0-aa78-bf8245a6ced6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specialization'])[1]/following::div[6]</value>
      <webElementGuid>fedbbec9-b4ad-4d29-afe1-38f747d05598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My News'])[1]/following::div[6]</value>
      <webElementGuid>caa283c1-8b14-4bfa-b77b-fc5a918fcbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Privacy Policy'])[1]/preceding::div[3]</value>
      <webElementGuid>bb167066-b92e-47a5-b9c4-3db2dd129d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/div</value>
      <webElementGuid>ecd2d25b-3d70-4245-b88d-b2742b52c577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'PageTitle' and (text() = '
	My Profile
' or . = '
	My Profile
')]</value>
      <webElementGuid>c06b0829-862d-4b5d-8d97-7b9cc45efbed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
