<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Title_ctl00ctl00ctl00GlobalBodyCo_7fbaad</name>
   <tag></tag>
   <elementGuidId>be569b57-87c9-489f-a488-158eefa018ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Job Title&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0826b78-9151-4746-8730-adf5cfb4ae4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$Title</value>
      <webElementGuid>79f432ed-509a-4044-b472-25ae1f6aabe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9d188c6-37e2-45e5-bdcd-ed8f1c982b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>crm01apr24job</value>
      <webElementGuid>e03ad9de-0094-4b7a-b1a1-d6a1b966d520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>4b8f85a3-4d7d-4821-a0ac-a849e3c22b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2a4803be-7b41-40b7-bd98-9756734903dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title&quot;)</value>
      <webElementGuid>844a335d-9252-4d1c-80f0-ba6782d987a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Title']</value>
      <webElementGuid>0efea835-91fa-4b6b-aaee-062e47728252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Title-form-group']/input</value>
      <webElementGuid>f52bcf6a-1a0e-4b1d-b447-a6513e8a81f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>b6e39bfc-2d42-4b26-8452-a5a2e974c5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$Title' and @type = 'text' and @id = 'Title']</value>
      <webElementGuid>7dd77188-ddb3-4ba0-9ffb-faf3ca31ba14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
