<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Thank you for your interest in becoming a_be487b</name>
   <tag></tag>
   <elementGuidId>22dea678-4893-4b5f-9a26-aa9bc8937ab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EditableArea1']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Thank you for your interest in becoming an Alliance Partner. Your application is&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b0002926-0f38-4caa-bd60-e681d781c509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for your interest in becoming an Alliance Partner. Your application is being reviewed, and we will get back to you within 14 days with an update on the status of your application.</value>
      <webElementGuid>b6b7cd7a-9b9a-4a2e-aaaf-48720a3064f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditableArea1&quot;)/p[1]</value>
      <webElementGuid>c3493cef-10e0-49af-9b62-95a415c8c24a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditableArea1']/p</value>
      <webElementGuid>e250a676-4022-4334-92ad-759cc617edba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Submitted'])[1]/following::p[1]</value>
      <webElementGuid>f44fa690-95e7-4e71-ae0b-afdee41965a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Your Country'])[1]/following::p[1]</value>
      <webElementGuid>93a94985-3880-4f3e-9bce-4884406828ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Privacy Policy'])[1]/preceding::p[2]</value>
      <webElementGuid>59942cd0-baf9-467d-a36e-31e10ea6a31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you for your interest in becoming an Alliance Partner. Your application is being reviewed, and we will get back to you within 14 days with an update on the status of your application.']/parent::*</value>
      <webElementGuid>339f8660-9bbd-40ee-8c07-4543c4410e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>a7384984-aeed-4424-baa9-11e463cd3fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Thank you for your interest in becoming an Alliance Partner. Your application is being reviewed, and we will get back to you within 14 days with an update on the status of your application.' or . = 'Thank you for your interest in becoming an Alliance Partner. Your application is being reviewed, and we will get back to you within 14 days with an update on the status of your application.')]</value>
      <webElementGuid>cbe1034b-4e48-498e-b42a-2d3631b652a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
