<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Portal Sign In_ctl00ctl00ctl00GlobalB_3cecb8</name>
   <tag></tag>
   <elementGuidId>78cbcd80-30fc-4378-b6f2-08b4a57f4262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GlobalBodyContent_ExternalBodyContent_BodyContent_LoginControl_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_LoginControl_Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22834494-f2b8-4c2a-94d8-b92162b6123b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$LoginControl$Password</value>
      <webElementGuid>3c98c683-a747-4bba-8f0a-5812c9d02a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>55f482ed-f017-4466-b8a4-af8a71724f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GlobalBodyContent_ExternalBodyContent_BodyContent_LoginControl_Password</value>
      <webElementGuid>d209c709-644d-433f-b852-b3070e0435ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1fb65564-2c9b-4a90-a13c-22f158754a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c26e5d89-7879-4a87-804c-96c797ee675e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GlobalBodyContent_ExternalBodyContent_BodyContent_LoginControl_Password&quot;)</value>
      <webElementGuid>9da3a11a-b054-4785-8c3f-039aae8047e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GlobalBodyContent_ExternalBodyContent_BodyContent_LoginControl_Password']</value>
      <webElementGuid>a5dfbd3e-4bfe-4ff3-879f-d1dc8316f306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='home_login']/div[2]/div[2]/input</value>
      <webElementGuid>a4ae503c-2737-4cf2-8d65-15dfc9676040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>ef9f55a6-45a9-4fef-9559-0c5381ee9971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$ExternalBodyContent$BodyContent$LoginControl$Password' and @type = 'password' and @id = 'GlobalBodyContent_ExternalBodyContent_BodyContent_LoginControl_Password' and @placeholder = 'Password']</value>
      <webElementGuid>ab36b6e2-eabc-440b-8ea5-10aa8463bea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
