<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Activity History_vfFrameId_1722545076962</name>
   <tag></tag>
   <elementGuidId>7e70f8a8-3f82-461e-ad82-6202b06ff70b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;vfFrameId_1722547377525&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[3]/div/force-aloha-page/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;vfFrameId_1722547377525&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>83dbd5d1-e37c-4d5e-b7a8-73d275fedbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fff67d72-ea55-46ea-a039-4c92dd6f30cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b2b17369-8ded-43e8-9156-5a81b695bd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>1184c4b0-2c5a-4e26-9ec9-587bff79b29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>7deba4f4-586b-418d-847f-30c46400b55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>94b454b8-958c-4807-a259-2a02948ce144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfFrameId_1722547377525</value>
      <webElementGuid>a8824408-2498-456c-99a7-11ae478e2cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>accessibility title</value>
      <webElementGuid>2923e1be-2561-4780-9c2c-cc0086891a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en-US</value>
      <webElementGuid>6b53e9f9-bae4-42c0-80e7-257e4ca4fdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *; microphone *; camera *; display-capture *</value>
      <webElementGuid>ed257b88-f38a-4165-a1bb-8177013303e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a909e432-2295-45bb-b67c-ab7a4254f298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;oneAlohaPage&quot;]/force-aloha-page[1]/div[@class=&quot;iframe-parent slds-template_iframe slds-card&quot;]/iframe[1]</value>
      <webElementGuid>8063f2fc-b5b2-4159-9861-79c93eb38646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>9d58a21dcc865990ee39a0e487993687</value>
      <webElementGuid>35c4cbd3-3400-41b3-8eed-8c3f83453f50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='vfFrameId_1722547377525']</value>
      <webElementGuid>5b9ce466-b5d7-42ad-8b6b-474922bffb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/force-aloha-page/div/iframe</value>
      <webElementGuid>033e77ac-9e49-484a-8604-34f5cb97a1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//force-aloha-page/div/iframe</value>
      <webElementGuid>bd2f1c53-cfa8-428b-9580-83b3418034ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'vfFrameId_1722547377525' and @title = 'accessibility title']</value>
      <webElementGuid>baa8351b-168a-4927-a106-6edb851cd46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='vfFrameId_1722546275378']</value>
      <webElementGuid>7a6e559d-71fa-49cb-8431-8ac1695affaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'vfFrameId_1722546275378' and @title = 'accessibility title']</value>
      <webElementGuid>755994a8-817b-4247-aba9-a632bfbd11b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='vfFrameId_1722545076962']</value>
      <webElementGuid>6c1d2a9a-9f85-41a4-af94-5f780798a8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'vfFrameId_1722545076962' and @title = 'accessibility title']</value>
      <webElementGuid>37cec509-e350-4bd0-bc02-417bf57d9330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
