<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gmail_selectContact</name>
   <tag></tag>
   <elementGuidId>627cd9b9-99bb-4e25-a55f-472bbc5f6b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0037X000012AsKEQA0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='0037X000012AsKEQA0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;crm01apr24 testupdate Dileep crm01apr24concty Alabama dsunkara+crm01apr24@logitech.com [Compose Gmail (New Window)Gmail] 1122334455 test154&quot;s] >> internal:role=radio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f90648de-cfa2-45fb-bded-07100fa8d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0037X000012AsKEQA0</value>
      <webElementGuid>90f9f3ed-86e6-4e00-8bb4-e3535b82b9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectContact</value>
      <webElementGuid>6b2c6c27-f701-457c-80d5-202fec740bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d8632826-702d-418f-ac5c-c1a16f206f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0037X000012AsKEQA0&quot;)</value>
      <webElementGuid>8cbea7de-06ed-4d37-a2f3-1f78730cd4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lead  Salesforce/iframe_Activity History_vfFrameId_1722545076962</value>
      <webElementGuid>791d668d-6219-4a80-931e-604fdc5a1a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='0037X000012AsKEQA0']</value>
      <webElementGuid>012498aa-4ea3-4466-bf75-41b6fc9668f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id43']/input</value>
      <webElementGuid>1128b901-801a-489d-9c87-d6b6e11fe7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>b4d2a28a-de6c-4a41-b1c2-3552526f98ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '0037X000012AsKEQA0' and @name = 'selectContact' and @type = 'radio']</value>
      <webElementGuid>3e4053b8-8ca0-4e46-aba1-5f189dc7ffd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
