<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__j_id0j_id2j_id3j_id5j_id6detailsj_id32</name>
   <tag></tag>
   <elementGuidId>41a54d15-fb3e-4195-8774-c3f4b57f50e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='j_id0:j_id2:j_id3:j_id5:j_id6:details:j_id32']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Partner Account&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44597867-e83a-4084-b508-6a2d99df86c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cls</value>
      <webElementGuid>1c4ec6bb-e618-4104-b65e-83b2ba82a550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:j_id2:j_id3:j_id5:j_id6:details:j_id32</value>
      <webElementGuid>cd90c609-2ef9-4a55-af31-dfc6026a5bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>c88c1faf-11ee-4df4-9bb3-76e6653c90a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_id0:j_id2:j_id3:j_id5:j_id6:details:j_id32</value>
      <webElementGuid>c5d0eebf-4213-46e9-b574-d41a9a806ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getPartnerContacts();</value>
      <webElementGuid>9eb0d65f-27fc-4373-933d-58420ce9a776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e723c255-b24c-48c6-ac99-dea1c422e36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f379041-dd0c-4249-89d8-e98614a17bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:j_id2:j_id3:j_id5:j_id6:details:j_id32&quot;)</value>
      <webElementGuid>2336ec8d-987b-4f24-83e8-d2299bf01382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lead  Salesforce/iframe_Activity History_vfFrameId_1722545076962</value>
      <webElementGuid>1b45f293-9df8-49c8-bd8c-4499a62b5dce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_id0:j_id2:j_id3:j_id5:j_id6:details:j_id32']</value>
      <webElementGuid>df155e9e-3ec3-4f8d-9cad-3d06cb0034f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_id0:j_id2:j_id3:j_id5:j_id6:details']/div/table/tbody/tr/td/div/span/input</value>
      <webElementGuid>f03f946d-09d4-48ce-9500-631d4b598bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>25fc058f-7008-41a3-bcc6-0d4e6cc5b935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_id0:j_id2:j_id3:j_id5:j_id6:details:j_id32' and @name = 'j_id0:j_id2:j_id3:j_id5:j_id6:details:j_id32' and @type = 'text']</value>
      <webElementGuid>0bc683bd-d626-4b09-8408-95a81ad16c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
