<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_crm01apr24 testupdate Dileep</name>
   <tag></tag>
   <elementGuidId>aee1bde7-c8ff-467a-bf21-b1b8ffcaa733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id45']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;crm01apr24 testupdate Dileep&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab8b7a86-d1c3-4ba9-9816-50533a80319f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id177</value>
      <webElementGuid>639f9263-7d70-403b-a762-16888e3e6fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>crm01apr24 testupdate Dileep</value>
      <webElementGuid>824f76b4-ba22-4de6-9d34-e3b273e04d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id177&quot;)</value>
      <webElementGuid>85530d65-05a5-402c-bbf4-4c42824c1fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lead  Salesforce/iframe_Activity History_vfFrameId_1722545076962</value>
      <webElementGuid>f0c639ac-fab6-43b6-8816-f5ad95688dd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id177']</value>
      <webElementGuid>988fb3f0-e23c-41d7-9929-1d9d87d1689b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id45']/span</value>
      <webElementGuid>82348339-951e-4898-8796-0815090b2c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::span[2]</value>
      <webElementGuid>63d2129b-44a7-452a-ac6d-8ad568cf1cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clint.young@impartner.com.invalid'])[1]/following::span[2]</value>
      <webElementGuid>5e2cbd78-1b62-4d0f-9900-d731b07127e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crm01apr24concty'])[1]/preceding::span[1]</value>
      <webElementGuid>72cd746d-6348-46df-bcb1-2e4adae68738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alabama'])[1]/preceding::span[2]</value>
      <webElementGuid>f9714d63-7aff-43e1-a6a7-9b6e8082d374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='crm01apr24 testupdate Dileep']/parent::*</value>
      <webElementGuid>70656b04-5260-4456-9fec-bf7a0e8d99d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>9bf4760a-d53b-4adb-ba19-36f3b4088306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id177' and (text() = 'crm01apr24 testupdate Dileep' or . = 'crm01apr24 testupdate Dileep')]</value>
      <webElementGuid>f56f1e10-497b-41cb-b52e-2c8a5783c026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id87']</value>
      <webElementGuid>060f5978-6cd2-4398-83ce-ac0eba89425a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id87' and (text() = 'crm01apr24 testupdate Dileep' or . = 'crm01apr24 testupdate Dileep')]</value>
      <webElementGuid>02b36da7-f069-422f-8038-e57134b08093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
