<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_crm01apr24 testupdate Dileep</name>
   <tag></tag>
   <elementGuidId>5c9071a9-9120-4b28-ac81-e109752b4731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id45']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;crm01apr24 testupdate Dileep&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>09fd3162-5434-4472-93d1-b35c9123df88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataCell</value>
      <webElementGuid>f5d1b203-7142-45a6-9f9d-e2368f464674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id45</value>
      <webElementGuid>210eb785-87ee-486e-a59b-8036ed2dcadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6830f89d-1b6c-4841-aa67-239a85832f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>crm01apr24 testupdate Dileep</value>
      <webElementGuid>0f4b182e-4dea-4257-97bc-c2671adec7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id45&quot;)</value>
      <webElementGuid>e776d234-c9ee-4b2b-bfc4-194581538412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lead  Salesforce/iframe_Activity History_vfFrameId_1722545076962</value>
      <webElementGuid>db6b5998-6541-4366-a710-12b1199ddd93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id45']</value>
      <webElementGuid>34547b82-6f15-45b3-a032-fc32afae1f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:tb']/tr[2]/td[2]</value>
      <webElementGuid>f202fcfd-50d0-4fb2-94b2-8b663ff560f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::td[4]</value>
      <webElementGuid>dd58a007-2a2d-4e28-984f-640da9a6f625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clint.young@impartner.com.invalid'])[1]/following::td[4]</value>
      <webElementGuid>fd6cb725-c7a8-4e73-a77a-b15d6633e853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crm01apr24concty'])[1]/preceding::td[1]</value>
      <webElementGuid>948e997e-3132-4d16-8571-6486703c6c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>2e9b7a76-3f65-41a1-9452-a2b9d1268977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id45' and (text() = 'crm01apr24 testupdate Dileep' or . = 'crm01apr24 testupdate Dileep')]</value>
      <webElementGuid>37dca044-a43d-46a3-bbcc-2ba34ea53ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
