<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Clint Test Young</name>
   <tag></tag>
   <elementGuidId>a7d4a977-9f96-4d99-92f5-636d67667e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id45']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Clint Test Young&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cf22237b-e154-4c2a-821e-d2e1676f74a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataCell</value>
      <webElementGuid>57f84007-2693-42b7-bc7d-dc1bc913aa42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id45</value>
      <webElementGuid>7fba12f0-5371-4ad3-b383-da19df55f061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d1897da-6ea2-480b-8660-898f5cd5a172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clint Test Young</value>
      <webElementGuid>d84a6f11-7b73-4bfb-ad5f-2132ccf42e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id45&quot;)</value>
      <webElementGuid>6e1db0d2-bcc3-4f0a-8746-60497f16b421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lead  Salesforce/iframe_Activity History_vfFrameId_1722545076962</value>
      <webElementGuid>9d1086b2-4080-4a15-8136-17f34278e948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id45']</value>
      <webElementGuid>e3d99883-0006-4331-96ba-f53c01140d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:tb']/tr/td[2]</value>
      <webElementGuid>3bca5460-cc16-494d-97aa-7c6e44a0069e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Title'])[1]/following::td[2]</value>
      <webElementGuid>8dbefe4b-0e78-4e51-a2fd-298d36a60327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::td[2]</value>
      <webElementGuid>a78f65bc-6c86-4321-870e-cc119c758ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crm01apr24cty'])[1]/preceding::td[1]</value>
      <webElementGuid>409b4716-955b-4584-b623-d439d19dea5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td[2]</value>
      <webElementGuid>0b9bd489-d473-416a-8201-cd9ed7505851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id45' and (text() = 'Clint Test Young' or . = 'Clint Test Young')]</value>
      <webElementGuid>15b603c4-a946-40e9-b11b-e34c30542ac9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
