<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Gmail_j_id0j_id2j_id3j_id5j_id6j_id35j_i_006642</name>
   <tag></tag>
   <elementGuidId>d2ced8bb-97c1-496e-90f5-8718abd2a55d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id43']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;j_id0\:j_id2\:j_id3\:j_id5\:j_id6\:j_id35\:j_id42\:1\:j_id43&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1918592c-de52-413f-a641-e14d36fcedea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataCell</value>
      <webElementGuid>4947679c-e6ad-4dbc-a4a4-2c62d8cf4628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id43</value>
      <webElementGuid>7bb945f4-9693-4933-a9c2-190ada569d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>21fa2c67-8dbf-4df9-a0d3-15f2bddc08c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1%</value>
      <webElementGuid>de8d4244-9a03-478b-b69b-aba223174472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id43&quot;)</value>
      <webElementGuid>6bd70517-df03-4ba8-9baf-bffe380241a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lead  Salesforce/iframe_Activity History_vfFrameId_1722545076962</value>
      <webElementGuid>3d90c99d-afa6-49ad-a080-38f043bfa2b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id43']</value>
      <webElementGuid>a4458597-1e91-4cc0-9cdf-432248324639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:tb']/tr[2]/td</value>
      <webElementGuid>5c7f09e8-5acd-497d-93da-a2d487fe4cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::td[3]</value>
      <webElementGuid>2cfff8e1-a4d1-406a-a4b5-9ee7b4b0652a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clint.young@impartner.com.invalid'])[1]/following::td[3]</value>
      <webElementGuid>94643c8b-5597-4336-bec5-13880aea633e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crm01apr24 testupdate Dileep'])[1]/preceding::td[1]</value>
      <webElementGuid>0fdb8088-8ac1-4956-976e-f93287cfbf2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crm01apr24concty'])[1]/preceding::td[2]</value>
      <webElementGuid>be26311b-a93f-4c78-ac7d-ad194f997347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>8ad4356c-7b75-4a57-9722-f3a6f9d0af9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:1:j_id43']</value>
      <webElementGuid>05a960c6-9b2d-43df-aa4f-9389baefc7c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
