<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Job Title_j_id0j_id2j_id3j_id5j_id6j_id3_ef3782</name>
   <tag></tag>
   <elementGuidId>413d531e-bc50-429c-993d-32250813a37f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id43']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;j_id0\:j_id2\:j_id3\:j_id5\:j_id6\:j_id35\:j_id42\:0\:j_id43&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>94306f3a-157d-4bb6-9b35-7cc3f581e7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataCell</value>
      <webElementGuid>a167ba94-681d-4d15-9183-41f788950770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id43</value>
      <webElementGuid>9295067c-bcd9-4897-90a8-db3216c32d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>152bc204-16ac-4f27-a99f-a3f32b60c633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1%</value>
      <webElementGuid>47aab4a9-7060-4c3e-b292-fb4c35812281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id43&quot;)</value>
      <webElementGuid>521b9872-451c-4e13-9c42-1126b317c691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lead  Salesforce/iframe_Activity History_vfFrameId_1722545076962</value>
      <webElementGuid>5065b150-6797-4bee-808a-04413aa71361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id43']</value>
      <webElementGuid>75ff163f-c693-490b-b71b-c98aab20b29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:tb']/tr/td</value>
      <webElementGuid>b46e0475-223f-44cc-aaa5-0fdbb3d3270e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Title'])[1]/following::td[1]</value>
      <webElementGuid>c4a16c17-dc81-4080-8738-634688aefec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::td[1]</value>
      <webElementGuid>6b970142-e744-446b-9f4c-2c923fe2a0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clint Test Young'])[1]/preceding::td[1]</value>
      <webElementGuid>2f0f50fb-93af-4448-ac1c-9f3f3072ab0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crm01apr24cty'])[1]/preceding::td[2]</value>
      <webElementGuid>3cf84690-d2ec-4e47-ba46-825cb50fecea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td</value>
      <webElementGuid>5250c08e-4d64-4f2e-827c-068475a36389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'j_id0:j_id2:j_id3:j_id5:j_id6:j_id35:j_id42:0:j_id43']</value>
      <webElementGuid>a1f4ea1c-7581-40df-a477-3372644f4c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
