<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StateProvince_province</name>
   <tag></tag>
   <elementGuidId>07026138-754b-40d2-9a57-17faec9edd68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-290</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;State/Province&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d149da8-7bdb-44b5-90a6-c9bd8ee2c5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-combobox__input slds-input slds-combobox__input-value</value>
      <webElementGuid>53980b3a-188b-4de0-84b2-bb2e0cd24681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-input-290</value>
      <webElementGuid>1eb1fa81-e366-4f83-b451-f00dad8426aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca762c0e-0ddf-4d21-b4df-2e5ae4a4b9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>8f75c2cc-2a7c-4ee0-b1b9-99aa988e7d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>08892e38-6726-4218-a1b2-b59742bb9f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>03227d71-a0e8-4fc9-ba8a-30e06235f757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level1</value>
      <webElementGuid>eac03090-ce31-4f7e-8c07-60bb9adffb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>--None--</value>
      <webElementGuid>5b3c1fe9-474a-496e-b8b0-d3c8ae176a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>067b2055-35d1-453f-9200-0d2f72b1ab63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5e241d6-c457-4afd-9440-c82a9aa9a5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>16853f3f-9f2f-4060-bc41-27616ebbe06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>7e2bb3a5-9cc4-4f37-a7b0-c60e5c2f7926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>dropdown-element-290</value>
      <webElementGuid>a63e260c-5846-4a1f-b320-c1aa826b8d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>State/Province</value>
      <webElementGuid>4ba20445-ec45-43e6-9f3f-2fb27d1b6046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6547f4c1-f591-4793-a42b-7a05684492dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-element-290</value>
      <webElementGuid>8378f9f9-6728-44f2-a355-755a45f918bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-input-290&quot;)</value>
      <webElementGuid>ed61f267-ee8d-4b2f-aeec-da43ca26d248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combobox-input-290']</value>
      <webElementGuid>eef8ff65-3c00-4456-941b-9faf26e45c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-273']/dl/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-input-address/lightning-input-address/fieldset/div/div/div[4]/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div/div/div/input</value>
      <webElementGuid>770bf897-dcfc-4892-b718-9ca124e185c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div/div/div/input</value>
      <webElementGuid>899e9df7-94c8-472e-993b-79bb19bbe2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combobox-input-290' and @type = 'text' and @name = 'province']</value>
      <webElementGuid>2bb90430-5617-4d0f-9b38-2da24e2c6348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
