<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Email</name>
   <tag></tag>
   <elementGuidId>311853c3-f854-4d9c-aa7b-2762fb833e2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-179</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'input-179' and @name = 'Email' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//records-record-layout-row[5]/slot/records-record-layout-item/div/span/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f26918ae-cec8-4fbc-b849-1d0b884a3610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>3b826fed-423a-4071-b21b-324b71bfa1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-179</value>
      <webElementGuid>21af50f4-8cf3-4a61-a410-28ddd4cad262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-179</value>
      <webElementGuid>ed71e732-b281-4b62-b319-18c61c356135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>47fe3eb4-9f46-4cf6-a05d-5977493c15e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>1154d3bc-05c0-4c3d-8462-2255efee80c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>529b5e4d-efe5-46ff-8dff-2b8f74a7347e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ef88943-d333-4c31-b54c-2d21adfee23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a542bce-e9db-4ee0-a28c-2b2245f33c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-179&quot;)</value>
      <webElementGuid>12ca4257-685e-439a-85d4-e4a4f37e2f0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-179']</value>
      <webElementGuid>c81fe67e-d197-412f-8e07-eb21aa26c740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-124']/dl/slot/records-record-layout-row[5]/slot/records-record-layout-item/div/span/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>3fb15a8c-f8a3-4184-af24-d6e71a1903d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[5]/slot/records-record-layout-item/div/span/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>b1542185-3ea3-4de7-a6fc-7bcba48dd26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-179' and @name = 'Email' and @type = 'text']</value>
      <webElementGuid>07b0bf11-890e-4527-9d35-72e3836b5a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
