<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_ctl00ctl00ctl00GlobalBodyCont_1726c4</name>
   <tag></tag>
   <elementGuidId>e5c72f7f-1576-44ab-80e9-0a5977961490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MailingStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MailingStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;* Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd86c3c8-b258-458b-839b-5fca08b16f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingStreet</value>
      <webElementGuid>54b06c41-5728-4396-a182-44605279a017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c83d4dcd-e96e-4290-8f31-53d2a1896785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MailingStreet</value>
      <webElementGuid>59ea400f-3d8f-4c8b-8615-1231899ab321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f04d17e7-46bb-4c9a-82f7-3b9fff5b57e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MailingStreet&quot;)</value>
      <webElementGuid>abb6ac1c-5613-4181-9e22-815d07e0e60c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MailingStreet']</value>
      <webElementGuid>aaed6d70-0588-45c9-9669-082efe8b4971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MailingStreet-form-group']/input</value>
      <webElementGuid>fa8dd992-481f-4107-a69b-1efa33629d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>0b4a8bd0-ec71-4dc1-aefa-d35a6e8f87e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingStreet' and @type = 'text' and @id = 'MailingStreet']</value>
      <webElementGuid>1136e4a4-03d9-4d10-a4f0-d55126373899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
