<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_ctl00ctl00ctl00GlobalBodyContent_cbeb31</name>
   <tag></tag>
   <elementGuidId>ee000531-9bf8-4915-99af-bdd2923e315c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MailingCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MailingCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;* City&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8e2c9a0-9c2c-4e4b-8705-f886ef5f2daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingCity</value>
      <webElementGuid>98f0e755-c7f6-491d-a54c-ef38026d9f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>572cb0d1-b2eb-4be2-8cdc-66420c1a4862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MailingCity</value>
      <webElementGuid>c29933aa-de1a-4759-a7d7-074d3411e605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8dd32d71-aeb5-423b-b974-c0cf8f24d287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MailingCity&quot;)</value>
      <webElementGuid>a5d781cf-1ef9-49b2-bff9-d5fbea2e1197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MailingCity']</value>
      <webElementGuid>5633e240-cae9-4287-b579-322ad413237b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MailingCity-form-group']/input</value>
      <webElementGuid>fb7d21d6-a365-48fd-8f5f-668f8898e01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>6b188066-84cd-4b4d-8438-0b01e69a3dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingCity' and @type = 'text' and @id = 'MailingCity']</value>
      <webElementGuid>15c8e9a7-b1c9-44c4-a3f9-8c61b3e0725e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
