<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address 2_ctl00ctl00ctl00GlobalBodyCo_d09925</name>
   <tag></tag>
   <elementGuidId>e6dcd207-6c76-4cad-87e7-180f82fd936d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MailingSuite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MailingSuite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Address 2&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e93b6d78-bb64-4e0f-a307-b5d666631735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingSuite</value>
      <webElementGuid>34429b1b-9ba7-43ce-a064-9fa09d5d50b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>581149ec-198b-4cf6-bd7d-0f49e3a9c63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MailingSuite</value>
      <webElementGuid>e0303ad6-1e7d-46cc-bdc5-3595158251ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3885ca3c-3c43-41dc-8135-6036012d126f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MailingSuite&quot;)</value>
      <webElementGuid>7a1a3a84-55f4-4ae2-bd65-5753e7ec6090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MailingSuite']</value>
      <webElementGuid>7a3904cb-977e-4f44-a39e-8d9fe9679419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MailingSuite-form-group']/input</value>
      <webElementGuid>0850cf1c-e078-4310-a914-5fefcd6dade0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>7a55ad53-23a8-43bb-9a6c-67e2a60a3623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingSuite' and @type = 'text' and @id = 'MailingSuite']</value>
      <webElementGuid>15647656-56a0-4cef-9f8b-a7f7ee26b489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
