<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal Code_ctl00ctl00ctl00GlobalBody_3afcdb</name>
   <tag></tag>
   <elementGuidId>b77d9ae7-f7fe-46b8-994f-04b334df6df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MailingPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MailingPostalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;* Postal Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4178ba0a-bbd1-43c4-8f73-230dbcfb85f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingPostalCode</value>
      <webElementGuid>11e21e92-a079-424c-aad6-977acbf5189d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71d034a0-e7a9-422c-9ad5-0a1cd7c581e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MailingPostalCode</value>
      <webElementGuid>8ffc2470-bc0b-46df-ae58-b5a44190d327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f3800db1-afa3-4cef-af01-c718386ad625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MailingPostalCode&quot;)</value>
      <webElementGuid>92e0eafd-0d75-4847-a82f-3ddff1531dd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MailingPostalCode']</value>
      <webElementGuid>d075d125-c147-4558-87d5-e318eb732c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MailingPostalCode-form-group']/input</value>
      <webElementGuid>c072c902-cf47-4cda-afd5-2a8c47dd6bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>7ab57d16-2222-4d0c-ba2f-0282225a44c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$MailingPostalCode' and @type = 'text' and @id = 'MailingPostalCode']</value>
      <webElementGuid>367a5493-675a-4a26-b99d-101bd4b96746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
