<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Title_ctl00ctl00ctl00GlobalBodyCo_7fbaad</name>
   <tag></tag>
   <elementGuidId>994b89b9-b027-4f11-b1e3-f9c81acd4f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Job Title&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6ae13e8-7b7c-439d-a239-f55313f631cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$Title</value>
      <webElementGuid>4ff895be-3faa-4099-8653-0d40f4bd203b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9bc87040-2bd4-469e-b440-75e9af6da7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>ffc0e1b6-d705-4ecd-9624-74035346104e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c3c4dd5-0de8-4772-8a8f-9d906c7cceaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title&quot;)</value>
      <webElementGuid>bba5be53-5323-4690-a97d-c9892ae8afa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Title']</value>
      <webElementGuid>d79e5940-ca33-4c4e-a7a0-fccced30cdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Title-form-group']/input</value>
      <webElementGuid>6017127b-807e-44d9-ad0a-f1ce192c0a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>9bdb41aa-b3be-44c1-8e0b-7664a66b4e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ctl00$GlobalBodyContent$InternalBodyContent$BodyContent$Title' and @type = 'text' and @id = 'Title']</value>
      <webElementGuid>e41a1adc-420e-40dd-a24f-c676472f610f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
